name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  qodana-unclean-python:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Use qodana-python config'
        run: cp qodana_config/python.yaml qodana.yaml

      - name: 'Qodana Python Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: |
            --source-directory,test_cases/,
          artifact-name: qodana-python

  qodana-unclean-js:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: 'Use qodana-js config'
        run: cp qodana_config/js.yaml qodana.yaml

      - name: 'Qodana JS Scan'
        uses: JetBrains/qodana-action@v2023.2
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: |
            --source-directory,test_cases/,
          artifact-name: qodana-js
    