name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  qodana-unclean-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Use qodana-unclean-python config'
        run: cp qodana_config/unclean-python.yaml qodana.yaml

      - name: 'Qodana Unclean Python'
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: |
            --source-directory,test_cases/unclean/python,
          artifact-name: qodana-unclean-python
  qodana-unclean-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Use qodana-unclean-js config'
        run: cp qodana_config/unclean-js.yaml qodana.yaml

      - name: 'Qodana Unclean JS'
        uses: JetBrains/qodana-action@v2023.2
        with:
          args: |
            --source-directory,test_cases/unclean/js,
          artifact-name: qodana-unclean-js